---
- name: Deploy Tenant
  hosts: localhost
  vars_files: vars.yml
  tasks:
  - name: ACI - Create Lab Tenant
    aci_tenant:
      host: "{{ aci_hostname }}"
      username: "{{ aci_username }}"
      password: "{{ aci_password }}"
      validate_certs: no
      tenant: "{{ lab_name }}"
      description: "LAB - ACI Routing"
      state: present
    delegate_to: localhost
