---
- name: Deploy Tenant
  hosts: localhost
  vars_files: vars.yml
  tasks:
  - name: ACI - Remove Lab Tenant
    aci_tenant:
      host: "{{ aci_hostname }}"
      username: "{{ aci_username }}"
      password: "{{ aci_password }}"
      validate_certs: no
      tenant: "LABS-ACI-Routing{{ lab_number }}"
      state: absent
    delegate_to: localhost